[dependencies]
base = "0.9.4"

[package]
name = "xtended-numbers"
version = "0.2.1"
description = "Extended functionality for motoko number types, such as byte encoding"
repository = "https://github.com/edjCase/motoko_numbers"